# Base Image
FROM python:3.11.8

# Set working directory
WORKDIR /app

# Copy only requirements first (faster caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Set environment variable for Render's dynamic port
ENV PORT 8501
EXPOSE $PORT

# Run Streamlit app on Render's port and allow external access
CMD ["streamlit", "run", "app.py", "--server.port=$PORT", "--server.address=0.0.0.0"]
